# Image Augmentation

In [1]:
from keras.preprocessing.image import ImageDataGenerator,array_to_img
import cv2
import os
import numpy as np

Using TensorFlow backend.


In [3]:
path=r'C:\Users\Rvi\Desktop\demo'
image=os.listdir(path)
print(image)
image_path=os.path.join(path,image[0])
x=cv2.imread(image_path)
print(np.shape(x))
y=np.expand_dims(x,0)
print(np.shape(y))
aug_iter=gen.flow(y)
aug_image=[next(aug_iter)[0].astype(np.uint8) for i in range(20)]
print(aug_image[1])
for j in range(20):
        x=str(j)+".jpg"
        directory=os.path.join("C:\\Users\\Rvi\Desktop\\demo",x)
        cv2.imwrite(directory,aug_image[j])

['brain.JPG']
(360, 313, 3)
(1, 360, 313, 3)
[[[63 63 63]
  [63 63 63]
  [63 63 63]
  ...
  [61 59 59]
  [59 59 59]
  [59 59 59]]

 [[63 63 63]
  [63 63 63]
  [63 63 63]
  ...
  [61 59 59]
  [59 59 59]
  [59 59 59]]

 [[63 63 63]
  [63 63 63]
  [63 63 63]
  ...
  [61 59 59]
  [59 59 59]
  [59 59 59]]

 ...

 [[35 35 35]
  [35 35 35]
  [35 35 35]
  ...
  [67 51 29]
  [53 39 25]
  [47 37 29]]

 [[35 35 35]
  [35 35 35]
  [35 35 35]
  ...
  [55 41 27]
  [49 41 29]
  [47 39 35]]

 [[35 35 35]
  [35 35 35]
  [35 35 35]
  ...
  [49 41 29]
  [49 41 37]
  [45 39 39]]]


In [2]:
gen=ImageDataGenerator(rotation_range=10,width_shift_range=0.1
                       ,height_shift_range=0.1, shear_range=0.15, 
                       zoom_range=0.1,channel_shift_range=10.,horizontal_flip=True,vertical_flip=True,brightness_range=[1,5])

In [ ]:
path=r'C:\Users\Rvi\Downloads\brain\yes'
for i in iter(os.listdir(path)):
    path=os.path.join(path,i)
    print(i)
    image=np.expand_dims(cv2.imread(path),0)
    aug_iter=gen.flow(image)
    aug_image=[next(aug_iter)[0].astype(np.uint8) for i in range(25)]
    
    for j in range(25):
        x=i+str(j)+".jpg"
        directory=os.path.join("C:\\Users\\Rvi\Downloads\\brain\\aug_yes",x)
        cv2.imwrite(directory,aug_image[j])
    path=r'C:\Users\Rvi\Downloads\brain\yes'
    

Y1.jpg
Y10.jpg
Y100.JPG
Y101.jpg
Y102.jpg
Y103.jpg
Y104.jpg
Y105.jpg
Y106.jpg
Y107.jpg
Y108.jpg
Y109.JPG
Y11.jpg
Y111.JPG
Y112.JPG
Y113.JPG
Y114.JPG
Y115.JPG
Y116.JPG
Y117.JPG
Y12.jpg
Y120.JPG
Y13.jpg
Y14.jpg
Y146.JPG
Y147.JPG
Y148.JPG
Y15.jpg
Y153.jpg
Y154.jpg
Y155.JPG
Y156.JPG
Y157.JPG
Y158.JPG
Y159.JPG
Y16.JPG
Y160.JPG
Y161.JPG
Y162.jpg
Y163.JPG
Y164.JPG
Y165.JPG
Y166.JPG
Y167.JPG
Y168.jpg
Y169.jpg
Y17.jpg
Y170.JPG
Y18.JPG
Y180.jpg
Y181.jpg
Y182.JPG
Y183.jpg
Y184.JPG
Y185.jpg
Y186.jpg
Y187.jpg
Y188.jpg
Y19.JPG
Y192.JPG
Y193.JPG
Y194.jpg
Y195.JPG
Y2.jpg
Y20.jpg
Y21.jpg
Y22.jpg
Y23.JPG
Y24.jpg
Y242.JPG
Y243.JPG
Y244.JPG
Y245.jpg
Y246.JPG
Y247.JPG
Y248.JPG
Y249.JPG
Y25.jpg
Y250.jpg
Y251.JPG
Y252.jpg
Y253.JPG
Y254.jpg
Y255.JPG
Y256.JPG
Y257.jpg
Y258.JPG
Y259.JPG
Y26.jpg
Y27.jpg
Y28.jpg
Y29.jpg
Y3.jpg


In [76]:
path=r'C:\Users\Rvi\Downloads\brain\no'
for i in iter(os.listdir(path)):
    path=os.path.join(path,i)
    print(i)
    image=np.expand_dims(cv2.imread(path),0)
    aug_iter=gen.flow(image)
    aug_image=[next(aug_iter)[0].astype(np.uint8) for i in range(32)]
    
    for j in range(32):
        x=i+str(j)+".jpg"
        directory=os.path.join("C:\\Users\\Rvi\Downloads\\brain\\aug_no",x)
        cv2.imwrite(directory,aug_image[j])
    path=r'C:\Users\Rvi\Downloads\brain\no'
    

1 no.jpeg
10 no.jpg
11 no.jpg
12 no.jpg
13 no.jpg
14 no.jpg
15 no.jpg
17 no.jpg
18 no.jpg
19 no.jpg
2 no.jpeg
20 no.jpg
21 no.jpg
22 no.jpg
23 no.jpg
24 no.jpg
25 no.jpg
26 no.jpg
27 no.jpg
28 no.jpg
29 no.jpg
3 no.jpg
30 no.jpg
31 no.jpg
32 no.jpg
33 no.jpg
34 no.jpg
35 no.jpg
36 no.jpg
37 no.jpg
38 no.jpg
39 no.jpg
4 no.jpg
40 no.jpg
41 no.jpg
42 no.jpg
43 no.jpg
44no.jpg
45 no.jpg
46 no.jpg
47 no.jpg
48 no.jpeg
49 no.jpg
5 no.jpg
50 no.jpg
6 no.jpg
7 no.jpg
8 no.jpg
9 no.jpg
N1.JPG
N11.jpg
N15.jpg
N16.jpg
N17.jpg
N19.JPG
N2.JPG
N20.JPG
N21.jpg
N22.JPG
N26.JPG
N3.jpg
N5.jpg
N6.jpg
no 1.jpg
no 10.jpg
no 100.jpg
no 2.jpg
no 3.jpg
no 4.jpg
no 5.jpeg
no 6.jpg
no 7.jpeg
no 8.jpg
no 89.jpg
no 9.png
no 90.jpg
no 91.jpeg
no 92.jpg
no 923.jpg
no 94.jpg
no 95.jpg
no 96.jpg
no 97.jpg
no 98.jpg
no 99.jpg
no.jpg
No11.jpg
No12.jpg
No13.jpg
No14.jpg
No15.jpg
No16.jpg
No17.jpg
No18.jpg
No19.jpg
No20.jpg
No21.jpg
No22.jpg


In [18]:
n=input()
sum=0
for i in range(len(n)-1,-1,-1):
    if(sum<10):
        sum+=i
    else:
        break

12345


In [20]:
sum

10

'has'

In [1]:
chr(48+3)

'3'

C:\Users\Rvi\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: DeprecationWarning: `toimage` is deprecated!
`toimage` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use Pillow's ``Image.fromarray`` directly instead.
  # This is added back by InteractiveShellApp.init_path()
